name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/Miningcore/Miningcore.csproj
      
    - name: Build
      run: dotnet build src/Miningcore/Miningcore.csproj --no-restore --configuration Release
      
    - name: Test
      run: dotnet test src/Miningcore/Miningcore.csproj --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish src/Miningcore/Miningcore.csproj -c Release -o publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: miningcore
        path: publish/
